![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [1]:
# "import numpy as np" significa:
# "carga la librería numpy y de ahora en adelante llámala np"
# Le ponemos el alias "np" para no tener que escribir "numpy" cada vez
import numpy as np

# __version__ es un atributo especial que tienen las librerías
# con el número de versión instalada
print(np.__version__)

2.4.2


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [2]:
# np.arange(10) genera números del 0 al 9 (no llega al 10, igual que range)
my_array = np.arange(10)

print(my_array)
# resultado: [0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [4]:
# Para crear arrays rellenos de un valor usamos np.ones() (unos) o np.zeros() (ceros). Para True/False le decimos qué tipo de dato queremos con dtype=bool.
# np.ones((3,3)) crea un array de 3 filas x 3 columnas lleno de 1s
# dtype=bool convierte esos 1s en True (en booleano, 1 = True)
array_true = np.ones((3, 3), dtype=bool)

print(array_true)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [6]:
# my_array es [0 1 2 3 4 5 6 7 8 9]

# PASO 1: creamos la máscara
# % calcula el RESTO de dividir
# 1 % 2 = 1  (impar, resto 1)
# 2 % 2 = 0  (par, resto 0)
# != significa "distinto de"
mascara = my_array % 2 != 0

print(mascara)
# [False  True False  True False  True False  True False  True]
#    0      1     2     3     4     5     6     7     8     9

# PASO 2: aplicamos la máscara al array
# Donde hay True se queda, donde hay False desaparece
impares = my_array[mascara]
print(impares)
# [1 3 5 7 9]

# Se puede escribir en una sola línea:
impares = my_array[my_array % 2 != 0]
print(impares)
# [1 3 5 7 9]

[False  True False  True False  True False  True False  True]
[1 3 5 7 9]
[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [7]:
# .copy() crea una copia INDEPENDIENTE
# Si no usamos copy() y modificamos nuevo_array,
# también se modificaría my_array (comparten memoria)
nuevo_array = my_array.copy()

# Donde el elemento sea impar, lo sustituimos por -1
# Esto es: "en nuevo_array, en las posiciones donde haya impares, pon -1"
nuevo_array[nuevo_array % 2 != 0] = -1

print(nuevo_array)
# [ 0 -1  2 -1  4 -1  6 -1  8 -1]

print(my_array)
# [0 1 2 3 4 5 6 7 8 9]  # el original no ha cambiado

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [8]:
# ¿es impar? entonces pon -1
# ¿no es impar (es par)? entonces deja el valor original (my_array)
nuevo_array_where = np.where(my_array % 2 != 0, -1, my_array)

print(nuevo_array_where)
# [ 0 -1  2 -1  4 -1  6 -1  8 -1]

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [9]:
# reshape(filas, columnas)
# 2 filas x 5 columnas = 10 elementos 
array_2d = my_array.reshape(2, 5)

print(array_2d)
# [[0 1 2 3 4]
#  [5 6 7 8 9]]

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

## Ejercicio 16
Lee la imagen "numpy.png" usando Pillow, y guárdala en un array.

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

## Ejercicio 20
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?